import 'dart:ui';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import 'package:extend_crane_services/core/utils/responsive.dart';
import 'package:extend_crane_services/shared/global_widgets/custom_button.dart';
import 'package:extend_crane_services/shared/global_widgets/custom_text_field.dart';
import 'package:extend_crane_services/features/reports/presentation/pages/expense_analysis_page.dart';
import 'package:extend_crane_services/shared/global_widgets/premium_background.dart';
import 'package:extend_crane_services/features/auth/presentation/controllers/login_notifier.dart';
import 'package:extend_crane_services/features/finance/data/models/expense_model.dart';
import 'package:extend_crane_services/features/finance/data/repositories/finance_repository.dart';

class AddExpensePage extends ConsumerStatefulWidget {
  const AddExpensePage({super.key});

  @override
  ConsumerState<AddExpensePage> createState() => _AddExpensePageState();
}

class _AddExpensePageState extends ConsumerState<AddExpensePage> {
  final _formKey = GlobalKey<FormState>();

  final _titleController = TextEditingController();
  final _amountController = TextEditingController();
  final _dateController = TextEditingController();
  DateTime _selectedDate = DateTime.now();

  final List<String> _categories = ['Fuel', 'Maintenance', 'Permit', 'Salary', 'Others'];
  String? _selectedCategory;
  bool _isSaving = false;

  @override
  void initState() {
    super.initState();
    _dateController.text = DateFormat('MMM dd, yyyy').format(_selectedDate);
  }

  @override
  void dispose() {
    _titleController.dispose();
    _amountController.dispose();
    _dateController.dispose();
    super.dispose();
  }

  Future<void> _pickDate() async {
    final pickedDate = await showDatePicker(
      context: context,
      initialDate: _selectedDate,
      firstDate: DateTime.now().subtract(const Duration(days: 365)),
      lastDate: DateTime.now(),
      builder: (context, child) {
        return Theme(
          data: Theme.of(context).copyWith(
            colorScheme: Theme.of(context).colorScheme.copyWith(
              primary: Theme.of(context).colorScheme.secondary,
              onPrimary: Theme.of(context).colorScheme.primary,
            ),
          ),
          child: child!,
        );
      },
    );

    if (pickedDate != null && mounted) {
      setState(() {
        _selectedDate = pickedDate;
        _dateController.text = DateFormat('MMM dd, yyyy').format(_selectedDate);
      });
    }
  }

  void _applyQuickTag(String tag, String category) {
    setState(() {
      _titleController.text = tag;
      _selectedCategory = category;
    });
  }

  Future<void> _onSave() async {
    if (!_formKey.currentState!.validate()) return;
    if (_selectedCategory == null) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Please select a category')));
      return;
    }

    setState(() => _isSaving = true);

    try {
      final user = ref.read(currentUserProvider).value;
      if (user == null) throw 'User session loading. Please wait or relogin.';

      final amount = double.tryParse(_amountController.text.trim()) ?? 0.0;

      final expense = ExpenseModel(
        id: '', // Generated by repo
        operatorId: user.id,
        category: _selectedCategory!,
        amount: amount,
        description: _titleController.text.trim(),
        date: _selectedDate,
      );

      await ref.read(financeRepositoryProvider).addExpense(expense);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Expense Saved Successfully!'),
            backgroundColor: Colors.green,
          ),
        );
        Navigator.pop(context);
      }
    } catch (e) {
       if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error: $e'),
            backgroundColor: Colors.redAccent,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isSaving = false);
      }
    }
  }

  Widget _buildImagePlaceholder(ThemeData theme, double height) {
    return Container(
      height: height,
      decoration: BoxDecoration(
        color: Colors.white.withOpacity(0.05),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: Colors.white.withOpacity(0.05)),
      ),
      child: CustomPaint(
        painter: DashedRectPainter(color: Colors.white, strokeWidth: 1, gap: 5.0),
        child: InkWell(
          onTap: () {
            ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Image Picker Triggered')));
          },
          borderRadius: BorderRadius.circular(16),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Icon(Icons.add_a_photo, size: 48, color: theme.colorScheme.secondary.withOpacity(0.8)),
              const SizedBox(height: 12),
              const Text(
                'Upload Receipt / Photo',
                style: TextStyle(
                  color: Colors.white,
                  fontWeight: FontWeight.bold,
                ),
              ),
              const SizedBox(height: 4),
              const Text('PNG, JPG up to 5MB', style: TextStyle(color: Colors.white70, fontSize: 10)),
            ],
          ),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final isTablet = Responsive.isTablet(context);
    final userAsync = ref.watch(currentUserProvider);

    Widget formInputs = Form(
      key: _formKey,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Row(
            children: [
              Icon(Icons.description, color: theme.colorScheme.secondary),
              const SizedBox(width: 8),
              Text('Expense Details', style: theme.textTheme.displayLarge?.copyWith(fontSize: 18, color: Colors.white)),
            ],
          ),
          const SizedBox(height: 16),
          
          Wrap(
            spacing: 8,
            runSpacing: 8,
            children: [
              ActionChip(
                label: const Text('+ Diesel Refill'),
                backgroundColor: Colors.white.withOpacity(0.1),
                labelStyle: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold),
                onPressed: () => _applyQuickTag('Diesel Refill', 'Fuel'),
              ),
              ActionChip(
                label: const Text('+ Crane Service'),
                backgroundColor: Colors.white.withOpacity(0.1),
                labelStyle: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold),
                onPressed: () => _applyQuickTag('Crane Standard Service', 'Maintenance'),
              ),
              ActionChip(
                label: const Text('+ RTA Permit'),
                backgroundColor: Colors.white.withOpacity(0.1),
                labelStyle: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold),
                onPressed: () => _applyQuickTag('RTA Road Permit', 'Permit'),
              ),
            ],
          ),
          const SizedBox(height: 16),
          
          CraneInput(
            controller: _titleController,
            hintText: 'Expense Title',
            suffixIcon: const Icon(Icons.receipt_long),
            validator: (val) => val == null || val.isEmpty ? 'Required' : null,
          ),
          const SizedBox(height: 16),
          
          // Dropdown
          DropdownButtonFormField<String>(
            value: _selectedCategory,
            icon: const Icon(Icons.keyboard_arrow_down, color: Colors.white70),
            dropdownColor: const Color(0xFF0F172A), // Match gradient
            style: const TextStyle(color: Colors.white),
            decoration: InputDecoration(
              hintText: 'Select Category',
              hintStyle: const TextStyle(color: Colors.white38),
              filled: true,
              fillColor: Colors.white.withOpacity(0.05),
              border: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: const BorderSide(color: Colors.white12)),
              focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide(color: theme.colorScheme.secondary, width: 2)),
              contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
            ),
            items: _categories.map((cat) => DropdownMenuItem(value: cat, child: Text(cat))).toList(),
            onChanged: (val) {
              setState(() {
                _selectedCategory = val;
              });
            },
          ),
          
          const SizedBox(height: 16),
          CraneInput(
            controller: _amountController,
            hintText: 'Amount',
            keyboardType: const TextInputType.numberWithOptions(decimal: true),
            suffixIcon: const Icon(Icons.currency_exchange),
            validator: (val) => val == null || val.isEmpty ? 'Required' : null,
          ),
          const SizedBox(height: 16),
          CraneInput(
            controller: _dateController,
            hintText: 'Date of Expense',
            readOnly: true,
            onTap: _pickDate,
            suffixIcon: const Icon(Icons.calendar_today),
            validator: (val) => val == null || val.isEmpty ? 'Required' : null,
          ),
        ],
      ),
    );

    return PremiumScaffold(
      appBar: AppBar(
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios_new, color: Colors.white),
          onPressed: () => Navigator.pop(context),
        ),
        title: const Text('Add Expense', style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
        centerTitle: true,
        backgroundColor: Colors.transparent,
        elevation: 0,
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          physics: const BouncingScrollPhysics(),
          padding: EdgeInsets.symmetric(
            horizontal: Responsive.scale(context, 16).clamp(16.0, 32.0),
            vertical: 24,
          ),
          child: Center(
            child: ConstrainedBox(
              constraints: const BoxConstraints(maxWidth: 1000), 
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  // Total Expense Summary Card - Hidden during entry for focus if needed, but keeping for UI consistency
                  Card(
                    elevation: 0,
                    color: Colors.white.withOpacity(0.05),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(16),
                      side: BorderSide(color: Colors.white.withOpacity(0.05)),
                    ),
                    child: Container(
                      padding: const EdgeInsets.all(24),
                      child: Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          const Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text('Recording Expense', style: TextStyle(color: Colors.white70, fontSize: 12)),
                              SizedBox(height: 8),
                              Text('Operator Insight', style: TextStyle(color: Colors.white, fontSize: 18, fontWeight: FontWeight.bold)),
                            ],
                          ),
                          Container(
                            padding: const EdgeInsets.all(12),
                            decoration: BoxDecoration(color: Colors.amber.withOpacity(0.1), shape: BoxShape.circle),
                            child: const Icon(Icons.account_balance_wallet, color: Colors.amber, size: 32),
                          ),
                        ],
                      ),
                    ),
                  ),
                  
                  const SizedBox(height: 32),
                  
                  if (isTablet)
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Expanded(flex: 5, child: formInputs),
                        const SizedBox(width: 32),
                        Expanded(flex: 4, child: _buildImagePlaceholder(theme, Responsive.screenHeight(context) * 0.4)),
                      ],
                    )
                  else
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.stretch,
                      children: [
                        formInputs,
                        const SizedBox(height: 24),
                        _buildImagePlaceholder(theme, Responsive.screenHeight(context) * 0.25),
                      ],
                    ),
                    
                  SizedBox(height: Responsive.screenHeight(context) * 0.05),
                ],
              ),
            ),
          ),
        ),
      ),
      bottomNavigationBar: SafeArea(
        child: Container(
          padding: EdgeInsets.symmetric(
            vertical: 16,
            horizontal: Responsive.scale(context, 16).clamp(16.0, 32.0),
          ),
          decoration: BoxDecoration(
            color: Colors.white.withOpacity(0.05),
            border: Border(top: BorderSide(color: Colors.white.withOpacity(0.05))),
          ),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Expanded(
                child: Center(
                  child: CraneButton(
                    text: _isSaving ? 'Saving...' : 'Save Expense',
                    icon: _isSaving ? Icons.hourglass_top : Icons.save,
                    onPressed: _onSave,
                    isLoading: _isSaving || !userAsync.hasValue,
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class DashedRectPainter extends CustomPainter {
  final Color color;
  final double strokeWidth;
  final double gap;

  DashedRectPainter({required this.color, required this.strokeWidth, required this.gap});

  @override
  void paint(Canvas canvas, Size size) {
    final paint = Paint()
      ..color = color.withOpacity(0.5)
      ..strokeWidth = strokeWidth
      ..style = PaintingStyle.stroke;

    var path = Path();
    path.addRRect(RRect.fromRectAndRadius(Rect.fromLTWH(0, 0, size.width, size.height), const Radius.circular(16)));

    PathMetrics pathMetrics = path.computeMetrics();
    Path dashedPath = Path();

    for (PathMetric pathMetric in pathMetrics) {
      double distance = 0.0;
      while (distance < pathMetric.length) {
        dashedPath.addPath(
          pathMetric.extractPath(distance, distance + gap),
          Offset.zero,
        );
        distance += gap * 2;
      }
    }

    canvas.drawPath(dashedPath, paint);
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) => false;
}
