import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import 'package:extend_crane_services/shared/global_widgets/premium_background.dart';
import 'package:extend_crane_services/shared/global_widgets/custom_button.dart';
import 'package:extend_crane_services/shared/global_widgets/custom_text_field.dart';
import 'package:extend_crane_services/features/auth/presentation/controllers/login_notifier.dart';
import 'package:extend_crane_services/features/finance/data/models/expense_model.dart';
import 'package:extend_crane_services/features/finance/data/repositories/finance_repository.dart';

class AddMaintenancePage extends ConsumerStatefulWidget {
  const AddMaintenancePage({super.key});

  @override
  ConsumerState<AddMaintenancePage> createState() => _AddMaintenancePageState();
}

class _AddMaintenancePageState extends ConsumerState<AddMaintenancePage> {
  final _formKey = GlobalKey<FormState>();
  final _amountController = TextEditingController();
  final _reasonController = TextEditingController();
  final _dateController = TextEditingController();
  DateTime _selectedDate = DateTime.now();
  bool _isSaving = false;

  @override
  void initState() {
    super.initState();
    _dateController.text = DateFormat('EEEE, dd MMMM yyyy').format(_selectedDate);
  }

  @override
  void dispose() {
    _amountController.dispose();
    _reasonController.dispose();
    _dateController.dispose();
    super.dispose();
  }

  Future<void> _selectDate(BuildContext context) async {
    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: _selectedDate,
      firstDate: DateTime(2024),
      lastDate: DateTime.now(),
      builder: (context, child) {
        return Theme(
          data: Theme.of(context).copyWith(
            colorScheme: Theme.of(context).colorScheme.copyWith(
                  primary: Colors.amber,
                  onPrimary: Colors.black,
                  surface: const Color(0xFF1A1A2E),
                  onSurface: Colors.white,
                ),
          ),
          child: child!,
        );
      },
    );
    if (picked != null && picked != _selectedDate) {
      setState(() {
        _selectedDate = picked;
        _dateController.text = DateFormat('EEEE, dd MMMM yyyy').format(_selectedDate);
      });
    }
  }

  Future<void> _saveMaintenance() async {
    if (!_formKey.currentState!.validate()) return;
    
    setState(() => _isSaving = true);
    
    try {
      final user = ref.read(currentUserProvider).value;
      if (user == null) throw 'User profile not sync yet. Try again in 3 seconds.';

      final amount = double.tryParse(_amountController.text.trim()) ?? 0.0;
      
      final expense = ExpenseModel(
        id: '', // Generated by repo
        operatorId: user.id,
        category: 'Maintenance',
        amount: amount,
        description: _reasonController.text.trim(),
        date: _selectedDate,
      );

      await ref.read(financeRepositoryProvider).addExpense(expense);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Maintenance Entry Saved Successfully!'),
            backgroundColor: Colors.green,
          ),
        );
        Navigator.pop(context);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error: $e'),
            backgroundColor: Colors.redAccent,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isSaving = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final userAsync = ref.watch(currentUserProvider);

    return PremiumScaffold(
      appBar: AppBar(
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios_new, color: Colors.white, size: 20,),
          onPressed: () => Navigator.pop(context),
        ),
        title: const Text(
          'Add Maintenance',
          style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold, fontSize: 20),
        ),
        backgroundColor: Colors.transparent,
        elevation: 0,
        centerTitle: true,
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(24.0),
          child: Form(
            key: _formKey,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                const Text(
                  'Amount in AED',
                  style: TextStyle(color: Colors.white70, fontWeight: FontWeight.bold, fontSize: 14),
                ),
                const SizedBox(height: 8),
                Row(
                  children: [
                    Container(
                      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
                      decoration: BoxDecoration(
                        color: const Color(0x1AFFFFFF),
                        borderRadius: const BorderRadius.only(
                          topLeft: Radius.circular(8),
                          bottomLeft: Radius.circular(8),
                        ),
                        border: Border.all(color: Colors.white12),
                      ),
                      child: const Text(
                        'AED',
                        style: TextStyle(color: Colors.amber, fontWeight: FontWeight.bold, fontSize: 13),
                      ),
                    ),
                    Expanded(
                      child: CraneInput(
                        controller: _amountController,
                        hintText: 'Enter amount (e.g. 500)',
                        keyboardType: TextInputType.number,
                        validator: (val) => val == null || val.isEmpty ? 'Required' : null,
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 24),

                // Description Field
                const Text(
                  'Description / Reason',
                  style: TextStyle(color: Colors.white70, fontWeight: FontWeight.bold, fontSize: 14),
                ),
                const SizedBox(height: 4),
                CraneInput(
                  controller: _reasonController,
                  hintText: 'e.g. Engine Oil Change, Tyre Repair',
                  maxLines: 3,
                  validator: (val) => val == null || val.isEmpty ? 'Please enter a reason' : null,
                ),
                const SizedBox(height: 24),

                // Date Picker (Auto-filled but editable)
                const Text(
                  'Date (Auto-filled)',
                  style: TextStyle(color: Colors.white70, fontWeight: FontWeight.bold, fontSize: 14),
                ),
                const SizedBox(height: 4),
                InkWell(
                  onTap: () => _selectDate(context),
                  child: IgnorePointer(
                    child: CraneInput(
                      controller: _dateController,
                      hintText: 'Select Date',
                      suffixIcon: const Icon(Icons.edit_calendar, color: Colors.amber),
                    ),
                  ),
                ),
                
                const SizedBox(height: 28),

                // Save Button
                CraneButton(
                  text: _isSaving ? 'Saving...' : 'Save Entry',
                  icon: _isSaving ? Icons.hourglass_top : Icons.check_circle_outline,
                  onPressed: _saveMaintenance,
                  isLoading: _isSaving || !userAsync.hasValue,
                ),
                
                const SizedBox(height: 10),
                Center(
                  child: TextButton(
                    onPressed: () => Navigator.pop(context),
                    child: const Text(
                      'Cancel',
                      style: TextStyle(color: Colors.white54),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

