// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIZWmPOdx7awJGF7A_gr4BiWepPOWVgIo',
    appId: '1:786775733802:web:a8bb3969ca4e77a37eb553',
    messagingSenderId: '786775733802',
    projectId: 'crane-data-management',
    authDomain: 'crane-data-management.firebaseapp.com',
    storageBucket: 'crane-data-management.firebasestorage.app',
    measurementId: 'G-N6WHM46YCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyM7v2CcKsL3rsENkI3Vwn62B7XrvCln4',
    appId: '1:786775733802:android:d17f35a6067635da7eb553',
    messagingSenderId: '786775733802',
    projectId: 'crane-data-management',
    storageBucket: 'crane-data-management.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS-1pLdxmc0hGeKas7mfJWiVrG-XfUDi0',
    appId: '1:786775733802:ios:b367b4b13501d8667eb553',
    messagingSenderId: '786775733802',
    projectId: 'crane-data-management',
    storageBucket: 'crane-data-management.firebasestorage.app',
    iosBundleId: 'com.example.extendCraneServices',
  );
}
