// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwCVXBPA0RgpgsJROPWnwmu86PmJatzug',
    appId: '1:116471709607:web:9ab9a9e95119655c0f0082',
    messagingSenderId: '116471709607',
    projectId: 'bahadar-crane-report-app',
    authDomain: 'bahadar-crane-report-app.firebaseapp.com',
    storageBucket: 'bahadar-crane-report-app.firebasestorage.app',
    measurementId: 'G-MN6FN43J8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa90lgoJWy1RUIJigyd12-auVqq6yimUU',
    appId: '1:116471709607:android:614114417b88bc220f0082',
    messagingSenderId: '116471709607',
    projectId: 'bahadar-crane-report-app',
    storageBucket: 'bahadar-crane-report-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwBmNhoaB4gnQdybQ_M8oqVmN1JVTx-8g',
    appId: '1:116471709607:ios:a358035c516e85b10f0082',
    messagingSenderId: '116471709607',
    projectId: 'bahadar-crane-report-app',
    storageBucket: 'bahadar-crane-report-app.firebasestorage.app',
    iosBundleId: 'com.example.extendCraneServices',
  );
}
