import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../../shared/global_widgets/custom_text_field.dart';
import 'package:extend_crane_services/core/themes/app_theme.dart';
import 'package:extend_crane_services/features/auth/presentation/controllers/login_notifier.dart';
import 'package:extend_crane_services/features/work_order/data/models/work_order_model.dart';
import 'package:extend_crane_services/features/work_order/data/repositories/work_repository.dart';

class DirectWorkModal extends ConsumerStatefulWidget {
  final WorkOrderModel? initialData;
  const DirectWorkModal({super.key, this.initialData});

  @override
  ConsumerState<DirectWorkModal> createState() => _DirectWorkModalState();
}

class _DirectWorkModalState extends ConsumerState<DirectWorkModal> {
  final _clientController = TextEditingController();
  final _serviceController = TextEditingController(text: '25 Ton Crane');
  final _locationController = TextEditingController();
  final _earningsController = TextEditingController();
  final _expenseController = TextEditingController(); // Fuel or Partner Payment
  
  bool _isOwnCrane = true; // Mode selection
  double _commission = 0.0;
  bool _isSaving = false;

  @override
  void initState() {
    super.initState();
    if (widget.initialData != null) {
      final data = widget.initialData!;
      _clientController.text = data.clientName;
      _locationController.text = data.siteLocation;
      _earningsController.text = data.totalPrice.toString();
      _expenseController.text = data.expenseAmount > 0 ? data.expenseAmount.toString() : '';
      // Assume "Own Crane" by default for edited tasks unless we have specific expense data.
      _isOwnCrane = true;
    }
    // Logic for real-time commission calculation
    _earningsController.addListener(_calculateCommission);
    _expenseController.addListener(_calculateCommission);
  }

  void _calculateCommission() {
    if (!_isOwnCrane) {
      final total = double.tryParse(_earningsController.text) ?? 0.0;
      final paid = double.tryParse(_expenseController.text) ?? 0.0;
      setState(() {
        _commission = (total - paid).clamp(0, double.infinity);
      });
    }
  }

  @override
  void dispose() {
    _clientController.dispose();
    _serviceController.dispose();
    _locationController.dispose();
    _earningsController.dispose();
    _expenseController.dispose();
    super.dispose();
  }

  Future<void> _handleSave() async {
    if (_locationController.text.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please provide a location'), backgroundColor: Colors.redAccent),
      );
      return;
    }

    setState(() => _isSaving = true);

    try {
      final userModel = ref.read(currentUserProvider).value;
      if (userModel == null) {
        throw 'Operator profile not found. Please relogin or wait for sync.';
      }

      final gross = double.tryParse(_earningsController.text) ?? 0.0;
      final exp = double.tryParse(_expenseController.text) ?? 0.0;
      final net = (gross - exp).clamp(0, double.infinity).toDouble();

      final workOrder = WorkOrderModel(
        id: widget.initialData?.id ?? '', // Generated by repo if empty
        workOrderId: widget.initialData?.workOrderId ?? '', // Generated by repo if empty
        operatorId: widget.initialData?.operatorId ?? userModel.id,
        operatorName: widget.initialData?.operatorName ?? userModel.fullName,
        clientName: _clientController.text.isEmpty ? 'Direct Client' : _clientController.text,
        siteLocation: _locationController.text,
        createdAt: widget.initialData?.createdAt ?? DateTime.now(),
        status: widget.initialData?.status ?? 'pending_approval',
        totalPrice: gross,
        expenseAmount: exp,
        netEarnings: net,
      );

      if (widget.initialData != null) {
        await ref.read(workRepositoryProvider).updateWorkOrder(workOrder);
      } else {
        await ref.read(workRepositoryProvider).createWorkOrder(workOrder);
      }

      if (mounted) {
        Navigator.pop(context);
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Direct Work Entry Saved! Admin Notified.'),
            backgroundColor: Colors.green,
          ),
        );
      }
    } catch (e) {
       if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error: $e'), backgroundColor: Colors.redAccent, duration: const Duration(seconds: 4)),
        );
      }
    } finally {
       if (mounted) {
        setState(() => _isSaving = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final userAsync = ref.watch(currentUserProvider);
    final canSave = userAsync.hasValue && !_isSaving;

    return Container(
      padding: EdgeInsets.only(
        bottom: MediaQuery.of(context).viewInsets.bottom + 24,
        left: 24,
        right: 24,
        top: 24,
      ),
      decoration: const BoxDecoration(
        gradient: AppTheme.premiumGradient,
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      child: SingleChildScrollView(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Center(
              child: Container(
                width: 50, height: 4,
                decoration: BoxDecoration(color: Colors.white24, borderRadius: BorderRadius.circular(2)),
              ),
            ),
            const SizedBox(height: 20),
            Row(
              children: [
                Expanded(
                  child: DirectModeToggle(
                    text: 'Own Crane',
                    icon: Icons.engineering, 
                    isActive: _isOwnCrane, 
                    onTap: () => setState(() => _isOwnCrane = true)
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: DirectModeToggle(
                    text: 'Another Person',
                    icon: Icons.handshake_outlined, 
                    isActive: !_isOwnCrane, 
                    onTap: () => setState(() {
                      _isOwnCrane = false;
                      _calculateCommission();
                    })
                  ),
                ),
              ],
            ),
            const SizedBox(height: 20),
            
            const DirectInputLabel(text: 'Client Name (Optional)'),
            CraneInput(
              controller: _clientController,
              hintText: 'e.g. Street Client',
              prefixIcon: const Icon(Icons.person_outline_rounded, size: 20, color: Colors.white70),
            ),
            
            const SizedBox(height: 15),
            const DirectInputLabel(text: 'Service Type'),
            CraneInput(
              controller: _serviceController,
              hintText: 'e.g. 25 Ton Crane',
              prefixIcon: const Icon(Icons.build_outlined, size: 20, color: Colors.white70),
            ),
            
            const SizedBox(height: 15),
            const DirectInputLabel(text: 'Location'),
            CraneInput(
              controller: _locationController,
              hintText: 'e.g. Musaffah M-12',
              prefixIcon: const Icon(Icons.location_on_outlined, size: 20, color: Colors.white70),
            ),
            
            const SizedBox(height: 15),
            Row(
              children: [
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const DirectInputLabel(text: 'Total Received (AED)'),
                      CraneInput(
                        controller: _earningsController,
                        hintText: '0',
                        keyboardType: TextInputType.number,
                        prefixIcon: const Padding(
                          padding: EdgeInsets.symmetric(vertical: 14, horizontal: 8),
                          child: Text('AED', style: TextStyle(color: Colors.amber, fontWeight: FontWeight.bold, fontSize: 12)),
                        ),
                      ),
                    ],
                  ),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      DirectInputLabel(text: _isOwnCrane ? 'Fuel Expense (AED)' : 'Paid To Partner (AED)'),
                      CraneInput(
                        controller: _expenseController,
                        hintText: '0',
                        keyboardType: TextInputType.number,
                        prefixIcon: const Padding(
                          padding: EdgeInsets.symmetric(vertical: 14, horizontal: 8),
                          child: Text('AED', style: TextStyle(color: Colors.redAccent, fontWeight: FontWeight.bold, fontSize: 12)),
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ),

            if (!_isOwnCrane) ...[
              const SizedBox(height: 16),
              Container(
                padding: const EdgeInsets.all(10),
                decoration: BoxDecoration(
                  color: const Color(0x1A4CAF50),
                  borderRadius: BorderRadius.circular(10),
                  border: Border.all(color: const Color(0x1A4CAF50)),
                ),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    const Text('My Commission:', style: TextStyle(color: Colors.greenAccent, fontWeight: FontWeight.bold, fontSize: 12)),
                    Text('AED ${_commission.toStringAsFixed(2)}', style: const TextStyle(color: Colors.white, fontWeight: FontWeight.w900, fontSize: 15)),
                  ],
                ),
              ),
            ],
            
            const SizedBox(height: 20),
            
            // TASK 3: Save Button
            ElevatedButton(
              onPressed: canSave ? _handleSave : null,
              style: ElevatedButton.styleFrom(
                backgroundColor: Colors.amber,
                foregroundColor: Colors.black,
                minimumSize: const Size(double.infinity, 60),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
                elevation: 8,
              ),
              child: userAsync.when(
                  data: (profile) => _isSaving 
                      ? const CircularProgressIndicator(color: Colors.black)
                      : const Text('Save Entry', style: TextStyle(fontWeight: FontWeight.w900, letterSpacing: 1.5, fontSize: 14)),
                  loading: () => const Text('Loading Profile...', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 12)),
                  error: (err, _) => const Text('Relode Profile', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 12, color: Colors.red)),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class DirectModeToggle extends StatelessWidget {
  final String text;
  final IconData icon;
  final bool isActive;
  final VoidCallback onTap;

  const DirectModeToggle({
    super.key,
    required this.text,
    required this.icon,
    required this.isActive,
    required this.onTap,
  });

  @override
  Widget build(BuildContext context) {
    return InkWell(
      onTap: onTap,
      child: Container(
        padding: const EdgeInsets.symmetric(vertical: 14),
        decoration: BoxDecoration(
          color: isActive ? const Color(0x33FFC107) : const Color(0x0DFFFFFF),
          borderRadius: BorderRadius.circular(12),
          border: Border.all(color: isActive ? Colors.amber : Colors.white12),
        ),
        child: Column(
          children: [
            Icon(icon, color: isActive ? Colors.amber : Colors.white38, size: 24),
            const SizedBox(height: 4),
            Text(
              text,
              style: TextStyle(
                color: isActive ? Colors.white : Colors.white38,
                fontSize: 12,
                fontWeight: isActive ? FontWeight.bold : FontWeight.normal,
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class DirectInputLabel extends StatelessWidget {
  final String text;

  const DirectInputLabel({
    super.key,
    required this.text,
  });

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 5, left: 4),
      child: Text(
        text,
        style: const TextStyle(color: Colors.white70, fontSize: 10, fontWeight: FontWeight.bold, letterSpacing: 1.0),
      ),
    );
  }
}

